name: deploy

on:
  push:
    branches:
      - "main"
      - "next"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  RELEASE_NAME: briofy-web
  RELEASE_NAMESPACE: briofy-web
  RELEASE_DOMAIN: briofy.net
  NEXT_RELEASE_DOMAIN: next.briofy.net

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  helm:
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Run Helm and Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade --install 
            "${{ github.event.repository.name }}.${{ env.BRANCH_NAME }}"
            --namespace ${{ env.RELEASE_NAMESPACE }}
            --set name="${{ env.RELEASE_NAME }}"
            --set domainName="${{ env.RELEASE_DOMAIN }}"
            --set image.repository="${{ env.IMG_NAME }}"
            --set image.tag="${{ env.IMG_TAG }}"
            --set tls.enabled="true"
            --set tls.clusterIssuer="cf-letsencrypt"
            --set tls.secretName="prod-${{ env.RELEASE_NAME }}-net-tls"
            --create-namespace
            .ci/chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'
